# install a couple of packages that we will need
# if you have them already, you can comment out these lines with a "#"
#install.packages("data.table") 
#install.packages("zoo")
#install.packages("CORElearn")
#install.packages("vegan")
#install.packages("mclust")
#install.packages("apcluster")
#install.packages("randomForest")
#install.packages("varSelRF")
#install.packages("evtree")
# install.packages("party")
install.packages('forecast', dependencies = TRUE)

library(randomForest)
library(party)
library(evtree)
library(varSelRF)
library(CORElearn)
require(vegan)
library(mclust)
library(apcluster)
library(cluster)
library(psych)
library(data.table)
library(zoo)
library(lubridate)
library(plyr)
library(ggplot2)
library(devtools)
library(forecast)
